# Generated by Django 5.0.1 on 2024-04-12 14:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_upload_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='files_upload',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
